---
- name: Debug ansible_os_family and ansible_distribution
  ansible.builtin.debug:
    msg: "Ansible runs on {{ ansible_os_family }}, {{ ansible_distribution }}."

- name: Initialize distribution-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - main.yml
  tags:
    - always

- name: Install required packages
  ansible.legacy.package:
    name:
      - grep
      - curl

- name: Import rkhunter tasks
  ansible.builtin.import_tasks:
    file: rkhunter.yml
  tags:
    - rkhunter
  when:
    - secure_rkhunter
    - ansible_distribution != 'Alpine'

- name: Import chkrootkit tasks
  ansible.builtin.import_tasks:
    file: chkrootkit.yml
  tags:
    - chkrootkit
  when:
    - secure_chkrootkit
    - ansible_distribution != 'Alpine'

- name: Set fact
  ansible.builtin.set_fact:
    ssh_dir: "{{ '/etc/ssh' is exists }}"

- name: Debug
  ansible.builtin.debug:
    var: ssh_dir

- name: Secure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags:
        - ssh
        - notest
  tags:
    - always
  when:
    - secure_ssh
    - ssh_dir is true
