---
- name: Install required packages
  ansible.legacy.package:
    name: grep

- name: Install Rootkit Hunter
  ansible.legacy.package:
    name:
      - rkhunter
      - chkrootkit
  when:
    - secure_rkhunter

- name: Secure SSH
  ansible.builtin.import_tasks:
    file: ssh.yml
  tags:
    - ssh
  when:
    - secure_ssh
