---
- name: Install required packages
  ansible.legacy.package:
    name:
      - grep
      - curl

- name: Import rkhunter tasks
  ansible.builtin.import_tasks:
    file: rkhunter.yml
  tags:
    - rkhunter
  when:
    - secure_rkhunter

- name: Import chkrootkit tasks
  ansible.builtin.import_tasks:
    file: chkrootkit.yml
  tags:
    - chkrootkit
  when:
    - secure_chkrootkit

- name: Secure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags:
        - ssh
  tags:
    - always
  when:
    - secure_ssh
