---
- name: Create /etc/ssh/sshd_config.d
  ansible.legacy.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: "0o700"
    owner: root
    group: root

- name: Restrict key exhcange
  ansible.legacy.template:
    src: ssh_audit_hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/ssh_audit_hardening.conf
    mode: "0o600"
    owner: root
    group: root
  notify: Restart sshd
