---
- name: Converge
  hosts: all
  vars:
    secure_ssh: false

  tasks:
    - name: Debug
      ansible.builtin.debug:
        var: secure_ssh

    - name: "Include sv0.secure"
      ansible.builtin.include_role:
        name: "sv0.secure"
