---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master
      - devel
  schedule:
    - cron: '30 1 * * 3'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          pip install -r requirements-test.txt

      - name: Lint code
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.repository }}"
    needs:
      - lint
    strategy:
      fail-fast: false

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          pip install -r requirements-test.txt

      - name: Run Molecule tests
        run: |
          molecule test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_REMOTE_TMP: '/tmp'
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          PY_COLORS: '1'

  galaxy:
    name: Galaxy
    runs-on: ubuntu-latest
    if:
      contains('
        refs/tags
        refs/heads/master'
      , github.ref)
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
    needs:
      - lint
      - molecule
