---
name: Galaxy Action

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      - "Main workflow"
    types:
      - completed

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - run: printenv
      # - name: galaxy
      #   uses: robertdebock/galaxy-action@1.2.1
      #   with:
      #     galaxy_api_key: ${{ secrets.galaxy_api_key }}
